version: '2'
services:

  bitwarden:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - domain=${domain}
    container_name: bitwarden
    hostname: bitwarden
    # environment:
    #   - TZ=Asia/Shanghai
    #   - DOMAIN=${domain}
    #   - SIGNUPS_ALLOWED=false
    #   - WEB_VAULT_ENABLED=true
    #   - INVITATIONS_ALLOWED=false
    #   - WEBSOCKET_ENABLED=true
    #   - ROCKET_WORKERS=20
    #   - SHOW_PASSWORD_HINT=false
    #   - LOG_FILE=/data/bitwarden.log
    #   - IP_HEADER=X-Real-IP
    volumes:
      - ./bitwarden/data:/data
      - ./nginx/cert/:/etc/nginx/cert/
      - ./nginx/html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    ports:
      - 35128:35128
    networks:
      bw:
        ipv4_address: 172.168.18.2
    restart: on-failure


networks:
  bw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.18.0/24
          gateway: 172.168.18.1
