version: '2'
services:

  bitwarden:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - domain=${domain}
    container_name: bitwarden
    hostname: bitwarden
    volumes:
      - ./bitwarden/data:/data
      - ./nginx/cert/:/etc/nginx/cert/
      - ./nginx/html:/usr/share/nginx/html
    ports:
      # HTTP 协议，仅测试用，有中间人攻击风险，生产环境不要暴露出来
      - 35127:35127
      # HTTPS 协议
      - 35128:35128
    networks:
      bw:
        ipv4_address: 172.168.18.2
    restart: on-failure


networks:
  bw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.18.0/24
          gateway: 172.168.18.1
